### PR TITLE
Use great-great-jekyll theme

### PR DESCRIPTION
**Pull request by katydecorah**

### CODE REVIEW

**Comment by katydecorah** [comment]
I didn't add an SVG icon, because I couldn't find or think of a good one. Any ideas?

**Comment by katydecorah** [comment]
One abstract idea is a pretzel: 🥨

**Comment by jsnmrs** [comment]
I'm not sure — more abstract ideas:
- paper clips 🖇
- kite 🪁
- ice cream 🍦

**Comment by katydecorah** [comment]
Going to merge since the logo isn't blocking this PR. I'll open a new issue with these logo ideas.

**Pull request merged**
